### ISSUE TITLE
Crash on Fabric 1.18.2

### ISSUE THREAD

**Issue by spoorn** [Skylortrexler/MegaParrot#6]
Was just flying around in creative mode and it crashed twice from this, I think when the mega parrot entity is rendered

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/1/22, 4:21 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot read field "locals" because "this.currentStatement" is null
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87)
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:124)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:302)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:73)
	at website.skylorbeck.minecraft.megaparrot.entity.MegaParrotModel.setLivingAnimations(MegaParrotModel.java:78)
	at website.skylorbeck.minecraft.megaparrot.entity.MegaParrotModel.setLivingAnimations(MegaParrotModel.java:12)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:154)
	at website.skylorbeck.minecraft.megaparrot.entity.MegaParrotRenderer.render(MegaParrotRenderer.java:30)
	at website.skylorbeck.minecraft.megaparrot.entity.MegaParrotRenderer.method_3936(MegaParrotRenderer.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by skylorbeck** [comment]
![image](https://user-images.githubusercontent.com/42103122/199841387-6a110ff9-ef4c-42f7-9b14-63c1ac66039b.png)
